import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ServiceSettingsSchema, type ServiceView, type TrendsView } from '../../../packages/shared/src/services';
import { api, date, money } from './api';
import type { SecureWrite } from './Settings';
type SearchResult = Awaited<ReturnType<typeof import('../../../packages/services/src/search').searchNews>>;

export function Services({ secure }: { secure: SecureWrite }) {
  const query = useQuery({ queryKey: ['services'], queryFn: () => api<ServiceView>('/services') });
  if (query.isPending) return <p className="empty">Memuat koneksi layanan…</p>;
  if (query.error) return <p className="error" role="alert">{query.error.message}</p>;
  return query.data && <ServiceForm key={query.data.version} data={query.data} secure={secure}/>;
}
function ServiceForm({ data, secure }: { data: ServiceView; secure: SecureWrite }) {
  const [config, setConfig] = useState(data.config), [key, setKey] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [result, setResult] = useState<unknown>(null);
  const [searchQuery,setSearchQuery] = useState(''), [searchResult,setSearchResult] = useState<SearchResult|null>(null);
  const client = useQueryClient();
  async function run(action: 'save'|'probe'|'search') {
    setBusy(true);setError('');if(action==='search')setSearchResult(null);
    try {
      if(action==='search') setSearchResult(await secure('/services/search',{query:searchQuery.trim()}) as SearchResult);
      else {const response=action==='probe'?await secure('/services/probe',{}):await secure('/services',{expectedVersion:data.version,config:ServiceSettingsSchema.parse(config),...(key?{apiKey:key}:{})},'PUT');setKey('');setResult(action==='probe'?response:{message:'Konfigurasi layanan tersimpan.'});}
      await Promise.all([client.invalidateQueries({queryKey:['services']}),client.invalidateQueries({queryKey:['trends']})]);
    } catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <div className="form">
    <article className="provider-card"><div className="section-head"><strong>Tavily / official search</strong><span className={'badge '+data.searchStatus}>{data.searchStatus}</span></div><p>Key: {data.hasTavilyKey?'terkonfigurasi':'belum diisi'} · sumber {data.keySource}</p><small>Hari ini {money(data.spentTodayUsd)} · bulan ini {money(data.spentMonthUsd)}</small>{data.probe&&<p className="muted">Probe {date(data.probe.checkedAt)}: {data.probe.message}</p>}</article>
    <p className="muted">Key disimpan terenkripsi. Budget mengikuti Research daily/monthly budget pada Risiko. Harga credit dipakai untuk reservasi biaya sebelum permintaan.</p>
    <fieldset><legend>SEARCH SERVICE</legend><label className="check"><input type="checkbox" checked={config.tavily.enabled} onChange={e=>setConfig({...config,tavily:{...config.tavily,enabled:e.target.checked}})}/>Aktifkan Tavily</label><div className="form-grid"><label>API key<input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={data.hasTavilyKey?'Kosong = pertahankan key':'Masukkan key Tavily'}/></label><label>USD / credit<input type="number" min="0.00000001" max="1" step="0.000001" value={config.tavily.costPerCreditUsd} onChange={e=>setConfig({...config,tavily:{...config.tavily,costPerCreditUsd:e.target.value}})}/></label></div></fieldset>
    <fieldset><legend>PUBLIC NEWS FEEDS</legend><label className="check"><input type="checkbox" checked={config.news.enabled} onChange={e=>setConfig({...config,news:{...config.news,enabled:e.target.checked}})}/>Aktifkan pengambilan berita</label><div className="form-grid"><label>Interval (detik)<input type="number" min="300" max="86400" value={config.news.intervalSeconds} onChange={e=>setConfig({...config,news:{...config.news,intervalSeconds:Number(e.target.value)}})}/></label><label>Usia maksimum (jam)<input type="number" min="1" max="24" value={config.news.maxAgeHours} onChange={e=>setConfig({...config,news:{...config.news,maxAgeHours:Number(e.target.value)}})}/></label></div><p className="muted">RSS/Atom HTTPS publik. Label primer adalah klasifikasi feed; isi tetap perlu verifikasi terhadap aturan market.</p>
    {config.news.feeds.map((feed,i)=><article className="provider-card feed-form" key={i}><div className="form-grid">{(['id','name','url'] as const).map(field=><label className={field==='url'?'wide':''} key={field}>{field==='id'?'ID unik':field==='name'?'Nama sumber':'URL feed'}<input type={field==='url'?'url':'text'} value={feed[field]} onChange={e=>setConfig({...config,news:{...config.news,feeds:config.news.feeds.map((f,index)=>index===i?{...f,[field]:e.target.value}:f)}})}/></label>)}</div><div className="actions">{(['enabled','primary'] as const).map(field=><label className="check" key={field}><input type="checkbox" checked={feed[field]} onChange={e=>setConfig({...config,news:{...config.news,feeds:config.news.feeds.map((f,index)=>index===i?{...f,[field]:e.target.checked}:f)}})}/>{field==='enabled'?'Aktif':'Sumber primer'}</label>)}<button className="danger" onClick={()=>{if(confirm(`Hapus konfigurasi feed ${feed.name||feed.id}?`))setConfig({...config,news:{...config.news,feeds:config.news.feeds.filter((_,index)=>index!==i)}})}}>Hapus feed</button></div></article>)}
    <button disabled={config.news.feeds.length>=10} onClick={()=>setConfig({...config,news:{...config.news,feeds:[...config.news.feeds,{id:'',name:'',url:'',enabled:true,primary:false}]}})}>Tambah feed</button></fieldset>
    {error&&<p className="error" role="alert">{error}</p>}{result!==null&&<pre className="record" role="status">{JSON.stringify(result,null,2)}</pre>}
    <div className="actions"><button className="primary" disabled={busy} onClick={()=>void run('save')}>{busy?'Memproses…':'Simpan layanan'}</button><button disabled={busy} onClick={()=>void run('probe')}>Probe konfigurasi tersimpan</button></div><small>Probe memakai konfigurasi tersimpan dan verifikasi owner. Key saja belum membuktikan koneksi.</small>
    <fieldset><legend>MANUAL NEWS SEARCH</legend><p className="muted">Maksimal enam sumber berita dari 24 jam terakhir. Memakai mode aktif, konfigurasi tersimpan, budget riset, dan verifikasi owner; permintaan dapat dikenai biaya.</p><label>Kata kunci<input type="search" maxLength={1000} value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Federal Reserve interest rate"/></label><button disabled={busy||!searchQuery.trim()||!data.hasTavilyKey||!data.config.tavily.enabled} onClick={()=>void run('search')}>Cari berita</button>{searchResult&&<><p className="muted">Diperiksa {date(searchResult.checkedAt)} · kredit {searchResult.credits??'belum dilaporkan'}</p>{!searchResult.items.length&&<p className="empty">Tidak ada hasil bertanggal valid dalam 24 jam terakhir.</p>}{searchResult.items.map(item=><article className="provider-card" key={item.url}><h3><a href={item.url} target="_blank" rel="noopener noreferrer">{item.title} ↗</a></h3><p>{item.excerpt}</p><small>Publikasi {date(item.publishedAt)} · belum diverifikasi</small></article>)}</>}</fieldset>
  </div>;
}
export function Trends() {
  const query=useQuery({queryKey:['trends'],queryFn:()=>api<TrendsView>('/trends'),refetchInterval:60000});
  const [keyword,setKeyword]=useState(''), [page,setPage]=useState(1);
  const term=keyword.trim().toLocaleLowerCase('id');
  const filtered=(query.data?.items??[]).filter(item=>!term||[item.title,item.excerpt,item.sourceName,...item.marketIds].join(' ').toLocaleLowerCase('id').includes(term));
  const pages=Math.max(1,Math.ceil(filtered.length/8)), currentPage=Math.min(page,pages);
  const visible=filtered.slice((currentPage-1)*8,currentPage*8);
  return <section className="panel trends"><div className="section-head"><div><span className="eyebrow">PUBLIC SOURCE MONITOR</span><h2>Berita & konteks terbaru</h2></div><span className="muted">Diperiksa {date(query.data?.checkedAt)}</span></div><p className="muted">Cuplikan belum terverifikasi. Pencocokan market adalah konteks, bukan sinyal trading atau bukti resolusi.</p>{query.isPending&&<p className="empty">Memuat sumber publik…</p>}{query.error&&<p className="error" role="alert">{query.error.message}</p>}{query.data?.errors.map(e=><p className="error" key={e.sourceId}>{e.sourceId}: {e.message}</p>)}<div className="trend-toolbar"><input type="search" aria-label="Cari berita tersimpan" placeholder="Cari judul, sumber, atau market…" value={keyword} onChange={e=>{setKeyword(e.target.value);setPage(1);}}/><span className="muted">{filtered.length} dari {query.data?.items.length??0} berita</span></div><div className="trend-grid">{visible.map(item=><article className="trend-item" key={item.id}><div className="section-head"><span className="eyebrow">{item.sourceName}</span><span className={'badge '+(item.freshness==='fresh'?'ready':'degraded')}>{item.freshness}</span></div><h3><a href={item.url} target="_blank" rel="noopener noreferrer">{item.title} ↗</a></h3><p>{item.excerpt||'Sumber tidak menyediakan cuplikan.'}</p><small>{item.primary?'Feed primer':'Feed sekunder'} · belum diverifikasi<br/>Publikasi {date(item.publishedAt)}<br/>Diambil {date(item.retrievedAt)} · berlaku hingga {date(item.freshUntil)}</small><div className="trend-matches">{item.marketIds.length?`${item.marketIds.length} market terkait: ${item.marketIds.join(', ')}`:'Tidak ada market cocok dalam snapshot saat ini'}</div></article>)}</div>{query.data&&!filtered.length&&<p className="empty">{term?"Tidak ada berita yang cocok dengan kata kunci.":"Belum ada berita tersimpan. Periksa pengaturan feed dan worker."}</p>}<footer className="trend-pagination"><span>Halaman {currentPage} dari {pages} · maksimal 8 berita per halaman</span><div className="actions"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Sebelumnya</button><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Berikutnya</button></div></footer></section>;
}
